/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Q2jvX35BnWA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Image from "next/image";
import Link from "next/link";

// Reduced suggested meme searches
const suggestedSearches = [
  "cat memes",
  "programming jokes",
  "AI fails"
];

export const NoImagesFound = ({ query }: { query: string }) => {
  // If there is no query, show suggestions and Powered by Upstash below them
  if (!query || query.trim() === "") {
    return (
      <div className="flex flex-col items-center space-y-8 mt-4">
        {/* Suggested searches section - directly below search box */}
        <div className="w-full max-w-xl mx-auto">
          <div className="flex flex-wrap justify-center gap-4">
            {suggestedSearches.map((suggestion, index) => (
              <Link 
                key={index} 
                href={`/?q=${encodeURIComponent(suggestion)}`}
                className="py-2 px-6 rounded-md bg-[#34d399]/20 hover:bg-[#34d399]/40 text-white transition-all text-base"
              >
                {suggestion}
              </Link>
            ))}
          </div>
        </div>
      
        {/* Horizontal layout with logo and text - positioned below with fixed position */}
        <div className="fixed bottom-8 flex items-center justify-center space-x-2" style={{marginTop: "880px"}}>
          <img
            src="/upstash-logo.svg"
            alt="Upstash Logo"
            width={40}
            height={40}
          />
          <h3 className="text-base font-medium text-[#34d399]">
            Powered by Upstash
          </h3>
        </div>
      </div>
    );
  }

  // Otherwise show the "No memes found" message
  return (
    <div className="text-center p-12">
      <h3 className="text-lg font-medium">No memes found</h3>
      <p className="text-sm text-gray-500 mt-2">
        No memes were found for &quot;{query}&quot;. Try searching for something
        else.
      </p>
    </div>
  );
};
